game_score: "5000"
cm3:
  some: some
  enabled: true
favorite:
  drink: "thumps"
  food: "biryani"
components:
  - frontend
  - db
  - catalogue
  - redis
  - user
  - cart
job:
  enabled: true
  containers:
    - name: sample
      file_name: db/schema.sql