apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
data:
  MONGO       : "true"
  MONGO_URL   : "mongodb://mongodb-dev.sandeepkumar0088.online:27017/catalogue"
  DB_TYPE     : "mongo"
  APP_GIT_URL : "https://github.com/roboshop-devops-project-v3/catalogue"
  DB_HOST     : "mongodb-dev.sandeepkumar0088.online"
  SCHEMA_FILE : "db/master-data.js"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    project: roboshop
    app: catalogue
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    project: roboshop
    app: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: catalogue
  template:
    metadata:
      labels:
        project: roboshop
        app: catalogue
    spec:
      containers:
        - name: catalogue
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
          envFrom:
            - configMapRef:
                name: catalogue
---
apiVersion: batch/v1
kind: Job
metadata:
  name: catalogue-schema
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: schema
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          env:
            - name: SCHEMA_FILE
              value: db/master-data.js
          envFrom:
            - configMapRef:
                name: catalogue
      restartPolicy: Never