apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq-dev.sandeepkumar0088.online"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    project: roboshop
    app: payment
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    project: roboshop
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: payment
  template:
    metadata:
      labels:
        project: roboshop
        app: payment
    spec:
      containers:
        - name: payment
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/payment
          envFrom:
            - configMapRef:
                name: payment