apiVersion: v1
kind: configMap
metadata:
  name: {{  .Release.Name  }}-config
data:
  myValue: "hello world"
    {{- with  .Values.favorites  }}
    drink: {{  .drink | default tea | quote }}
    food: {{ .food | upper | quote  }}
    release: {{  $.Release.Name  }}
    {{- end  }}
  toppings: |-
    {{- range .Values.components  }}
    - {{ . | title | quote  }}
    {{- end  }}
