apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
data:
  CART_ENDPOINT : "cart:8080"
  DB_HOST       : "mysql-dev.sandeepkumar0088.online"
  MYSQL_HOST    : "mysql-dev.sandeepkumar0088.online"
  REDIS_HOST    : "redis-dev.sandeepkumar0088.online"
  DB_USER       : "root"
  DB_PASS       : "RoboShop@1"
  DB_TYPE       : "mysql"
  APP_GIT_URL   : "https://github.com/roboshop-devops-project-v3/shipping"
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    project: roboshop
    app: shipping
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    project: roboshop
    app: shipping
spec:
  replicas: 3
#  strategy:
#    rollingUpdate:
#      maxUnavailable: 0
#      maxSurge: 1
#    type: RollingUpdate
  selector:
    matchLabels:
      project: roboshop
      app: shipping
  template:
    metadata:
      labels:
        project: roboshop
        app: shipping
    spec:
      containers:
        - name: shipping
          image: 389841108590.dkr.ecr.us-east-1.amazonaws.com/shipping
          imagePullPolicy: Always
#          lifecycle:
#            preStop:
#              exec:
#                command: [ "/bin/sh", "-c", "sleep 30" ]
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 10
            periodSeconds: 10
          resources:
            limits:
              cpu: "1000m"
              memory: "1500Mi"
            requests:
              cpu: "1000m"
              memory: "1500Mi"
          envFrom:
            - configMapRef:
                name: shipping
---
apiVersion: batch/v1
kind: Job
metadata:
  name: shipping-schema-{{ .Release.Revision }}
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: schema
          389841108590:
          image: 389841108590.dkr.ecr.us-east-1.amazonaws.com/shipping-db-image
          envFrom:
            - configMapRef:
                name: shipping
      restartPolicy: Never
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shipping-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50