apiVersion: v1
kind: ConfigMap
metadata:
  name: user
data:
  MONGO     : "true"
  REDIS_URL : "redis://redis-dev.sandeepkumar0088.online:6379"
  MONGO_URL : "mongodb://mongodb-dev.sandeepkumar0088.online:27017/users"
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    project: roboshop
    app: user
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    project: roboshop
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: user
  template:
    metadata:
      labels:
        project: roboshop
        app: user
    spec:
      containers:
        - name: user
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/user
          envFrom:
            - configMapRef:
                name: user